### ISSUE TITLE
Hi! I need a hand here

### ISSUE THREAD

**Issue by MichelDiz** [antonybudianto/express-firebase#1]
Well, I am looking into ways to connect my Express-based GraphQL API with Firebase Auth-based authorization. I think I got to the right place xD

I want to test your code - How do I authenticate by Postman?

Thanks!

Best regards

PS: I See! your project just work with the Token right? I need something who connects my client to FB Auth and give-me a Token. 'Cus What you are doing in your project I just did - But will make my code more clean.

**Comment by MichelDiz** [comment]
I found! Should be
http://127.0.0.1:8381/api/

Authorization = Token

I'm right now with a real Token but your code error give this:

 <body>
        <pre>Error: First argument to verifyIdToken() must be a Firebase ID token string.
            <br> &nbsp; &nbsp;at FirebaseAuthError.FirebaseError [as constructor] (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\firebase-admin\lib\utils\error.js:25:28)
            <br> &nbsp; &nbsp;at new FirebaseAuthError (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\firebase-admin\lib\utils\error.js:90:23)
            <br> &nbsp; &nbsp;at FirebaseTokenGenerator.verifyIdToken (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\firebase-admin\lib\auth\token-generator.js:97:19)
            <br> &nbsp; &nbsp;at Auth.verifyIdToken (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\firebase-admin\lib\auth\auth.js:104:37)
            <br> &nbsp; &nbsp;at firebaseAuthMiddleware (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\express-firebase-middleware\src\auth.middleware.js:9:22)
            <br> &nbsp; &nbsp;at Layer.handle [as handle_request] (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\express\lib\router\layer.js:95:5)
            <br> &nbsp; &nbsp;at trim_prefix (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\express\lib\router\index.js:317:13)
            <br> &nbsp; &nbsp;at F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\express\lib\router\index.js:284:7
            <br> &nbsp; &nbsp;at Function.process_params (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\express\lib\router\index.js:335:12)
            <br> &nbsp; &nbsp;at next (F:\Development\API DEVELOPMENT\API GraphQL\FIREBASEAPP\Express-Fire\express-firebase\node_modules\express\lib\router\index.js:275:10)
        </pre>
    </body>


My token is working in another project.

It's like

const Token = 'eyJhbGciOiJSUzI1NiIsImtpZCI6IjYxNWU1MzAwYTkwODNlNzBjMTY1NWY1ZThlYzA3ZTlmZDc3ZTJlOTAifQ.eyJpc3MiOiJodHRwczovL3NlY3VyZXRva2VuLmdvb2dsZS5jb20vcHJvamV0by1wcm9tb3RlcnMiLCJhdWQiOiJwcm9qZXRvLXByb21vdGVycyIsImF1dGhfdGltZSI6MTQ5MzY5OTMyNCwidXNlcl9pZCI6IlY5bnVJM0N2OHNiTlhoeHJYbPmkZfqXJj4EI_CzFlHE4Z2fhpDRsOYKOHG7BhmIgOjTO2Afmv6v4r6nSfzxxDTU-ojWDbWdk5w_FllEpknOa2jjnASLt3j4PAJ18ucU5tIx5mZI_hsgVnNWJxNwPWUYJdFQ72Q';

admin.auth().verifyIdToken(Token )
  .then(function(decodedToken) {
    var uid = decodedToken.uid;
    // ...
    console.log("Sucesso", decodedToken);
  }).catch(function(error) {
    // Handle error   
   // console.log("decodedToken:", tokenGer);
    console.log("Error verify IdToken:", error);

  });

**Comment by antonybudianto7** [comment]
The middleware is looking at the header, the header should be:
```
Authorization Bearer <your token>
```
