### ISSUE TITLE
[Question] Project Overview

### ISSUE THREAD

**Issue by Moikapy** [antonybudianto/express-firebase#2]
Hey,

Had a question about this repo, probably can do this, but needed confirmation haha. So was wanting to create a CMS using VueJS with an Express-Firebase backend by creating API to be used on multiple front-ends. would I be able to creat users and view DB content using this starter or would you recommend going a different route if I wanted to use Express and Firebase

**Comment by antonybudianto** [comment]
Hi, sorry for late reply.
This starter can serve as the base, and you can grow it to suit your requirements.
